In [4]:
age=22
print(type(age))
name ="Asha"
is_student= True
print(type(is_student))

<class 'int'>
<class 'bool'>

In [9]:
age=20
if age >=18:
  print("Adult")

Adult

In [24]:
age=16
if age>=18:
    print("Eligible")
else:
    print("Not Eligible")

Not Eligible

In [30]:
marks=72
if marks>=90:
    print("A+")
elif marks>=75:
    print("A")
elif marks>=60:
      print("B")
elif marks>=50:
        print("C")
else:
          print("Fail")

B

In [16]:
age=25
fare=80
if age>=18 and fare>=50:
  print("Condition satisfied")

Condition satisfied

In [20]:
age =25
survived =1
if age>=18:
  if survived== 1:
    print("Adult survivor")

Adult survivor

# L**ISTS**
ordered
indexed
mutable
can contain duplicate value
# **uses square bracket[]**

In [21]:
my_list =[]
my_list

[]

[]

In [22]:
ages =[22,38,36,35,35]
names=["Asha","Sachin","Utkarsh"]
mixed =[10,"Python",3.5,True]

In [23]:

print(ages)
print(names)
print(mixed)

[22, 38, 36, 35, 35]
['Asha', 'Sachin', 'Utkarsh']
[10, 'Python', 3.5, True]

In [35]:
print(ages[0])
print(ages[-1])
print(names[-1])
print(ages[1:4])
print(ages[1:])
print(ages[:2])
print(ages[::2])
print(mixed[::2])

22
35
Utkarsh
[38, 36, 35]
[38, 36, 35, 35]
[22, 38]
[22, 36, 35]
[10, 3.5]

In [42]:
print(ages)
ages[2]=27
print(ages)

[22, 38, 27, 35, 35]
[22, 38, 27, 35, 35]

In [41]:
print(names)
names.append("Tanvi")
print(names)

['Asha', 'Sachin', 'Utkarsh']
['Asha', 'Sachin', 'Utkarsh', 'Tanvi']

In [51]:
#insert
names=["Asha","Sachin","Utkarsh"]
names.insert(1,"Yashi")
print(names)
names.insert(0,"Rashi")
print(names)

['Asha', 'Yashi', 'Sachin', 'Utkarsh']
['Rashi', 'Asha', 'Yashi', 'Sachin', 'Utkarsh']

In [87]:
print(names)
names.extend(["Vansh","Vaibhav"])

['Rashi', 'Yashi']

In [88]:
print(names)

['Rashi', 'Yashi', 'Vansh', 'Vaibhav']

In [52]:
#removing/deleting items
names.remove("Asha")
print(names)

['Rashi', 'Yashi', 'Sachin', 'Utkarsh']

In [55]:
removed=names.pop(2)
print(removed)
print(names)

Sachin
['Rashi', 'Yashi']

In [56]:
print(ages)
del ages[1]
print(ages)

[22, 38, 27, 35, 35]
[22, 27, 35, 35]

In [57]:
numbers=[10,20,30]
numbers.clear()
print(numbers)

[]

In [58]:
numbers=[40,10,30,20,10]
print(len(numbers))

5

In [59]:
print(numbers.count(10))

2

In [60]:
print(numbers)
print(numbers.index(30))

[40, 10, 30, 20, 10]
2

In [61]:
print(numbers)
print(10 in numbers)

[40, 10, 30, 20, 10]
True

In [62]:
print(50 in numbers)

False

In [63]:
print(max(numbers))

40

In [64]:
print(min(numbers))

10

In [67]:
print(sum(numbers))

110

In [66]:
numbers.sort()

In [68]:
print(numbers)

[10, 10, 20, 30, 40]

In [69]:
numbers.reverse()
print(numbers)

[40, 30, 20, 10, 10]

In [79]:
students =[

      ["Tanvi",21,"CSE"],
       ["Utkarsh",22,"CSE"],
       ["Yashi",19,"ECE"]

]

In [71]:
print(students[0])

['Tanvi', 21, 'CSE']

In [72]:
print(students[0][0])

Tanvi

In [77]:
print(students[2][2])

ECE

In [78]:
print(students[-1][-1])

ECE

In [80]:
students[0][1]=22
print(students)

[['Tanvi', 22, 'CSE'], ['Utkarsh', 22, 'CSE'], ['Yashi', 19, 'ECE']]

In [81]:
students.append(["Sachin",23,"IT"])

In [82]:
print(students)

[['Tanvi', 22, 'CSE'], ['Utkarsh', 22, 'CSE'], ['Yashi', 19, 'ECE'], ['Sachin', 23, 'IT']]

In [83]:
for student in students:
  print(student)

['Tanvi', 22, 'CSE']
['Utkarsh', 22, 'CSE']
['Yashi', 19, 'ECE']
['Sachin', 23, 'IT']

In [86]:
for value in student:
  print(value)

Sachin
23
IT

In [90]:
#combining lists with conditions
marks=[35,62,81,45,90]
for mark in marks:
  if mark>=50:
    print(mark,"Pass")
  else:
    print(mark,"Fail")

35 Fail
62 Pass
81 Pass
45 Fail
90 Pass

# MAKE A **DATAFRAME**

In [92]:
import pandas as pd
data={
    "Customer":["A1","A2","A3","A4","A5"],
    "Age":[22,35,28,40,55],
    "City":["Delhi","Mathura","Lucknow","Varanasi","Agra"],
    "Amount":[1200,3500,7800,4200,9500],
    "Rating":[4.53,3.5,2,4,5]
}
df=pd.DataFrame(data)
print(df)

  Customer  Age      City  Amount  Rating
0       A1   22     Delhi    1200    4.53
1       A2   35   Mathura    3500    3.50
2       A3   28   Lucknow    7800    2.00
3       A4   40  Varanasi    4200    4.00
4       A5   55      Agra    9500    5.00

In [95]:
df.loc[0:3,["Customer","City","Amount"]]

  Customer      City  Amount
0       A1     Delhi    1200
1       A2   Mathura    3500
2       A3   Lucknow    7800
3       A4  Varanasi    4200

In [96]:
df.loc[df["Amount"]>5000],["Customer","Amount"]

(  Customer  Age     City  Amount  Rating
 2       A3   28  Lucknow    7800     2.0
 4       A5   55     Agra    9500     5.0,
 ['Customer', 'Amount'])

In [97]:
#first 5 rows and first 3 columns
df.iloc[0:5,0:3]

  Customer  Age      City
0       A1   22     Delhi
1       A2   35   Mathura
2       A3   28   Lucknow
3       A4   40  Varanasi
4       A5   55      Agra